# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{newplugin}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jinzhu"]
  s.date = %q{2010-07-15}
  s.default_executable = %q{newplugin}
  s.description = %q{make create a new rails plugin dead easy}
  s.email = %q{wosmvp@gmail.com}
  s.executables = ["newplugin"]
  s.extra_rdoc_files = [
    "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/generators/app/USAGE",
     "lib/generators/app/app_generator.rb",
     "lib/generators/app/templates/MIT-LICENSE",
     "lib/generators/app/templates/README",
     "lib/generators/app/templates/Rakefile",
     "lib/generators/app/templates/init.rb",
     "lib/generators/app/templates/install.rb",
     "lib/generators/app/templates/lib/module.rb",
     "lib/generators/app/templates/tasks/tasks.rake",
     "lib/generators/app/templates/test/app_root/app/controllers/application.rb",
     "lib/generators/app/templates/test/app_root/app/controllers/application_controller.rb",
     "lib/generators/app/templates/test/app_root/config/boot.rb",
     "lib/generators/app/templates/test/app_root/config/database.yml",
     "lib/generators/app/templates/test/app_root/config/environment.rb",
     "lib/generators/app/templates/test/app_root/config/environments/in_memory.rb",
     "lib/generators/app/templates/test/app_root/config/environments/mysql.rb",
     "lib/generators/app/templates/test/app_root/config/environments/postgresql.rb",
     "lib/generators/app/templates/test/app_root/config/environments/sqlite.rb",
     "lib/generators/app/templates/test/app_root/config/environments/sqlite3.rb",
     "lib/generators/app/templates/test/app_root/config/initializers/plugin.rb",
     "lib/generators/app/templates/test/app_root/config/routes.rb",
     "lib/generators/app/templates/test/test_helper.rb",
     "lib/generators/app/templates/uninstall.rb",
     "lib/generators/controller/USAGE",
     "lib/generators/controller/controller_generator.rb",
     "lib/generators/controller/templates/controller.rb",
     "lib/generators/migration/USAGE",
     "lib/generators/migration/migration_generator.rb",
     "lib/generators/migration/templates/migration.rb",
     "lib/generators/model/USAGE",
     "lib/generators/model/model_generator.rb",
     "lib/generators/model/templates/fixtures.yml",
     "lib/generators/model/templates/migration.rb",
     "lib/generators/model/templates/model.rb",
     "lib/generators/scaffold/USAGE",
     "lib/generators/scaffold/scaffold_generator.rb",
     "lib/newplugin.rb",
     "test/test_helper.rb",
     "test/test_new_plugin.rb"
  ]
  s.homepage = %q{http://github.com/jinzhu/newplugin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{make create a new rails plugin dead easy}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_new_plugin.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

